CREATE INDEX idx_bemovi_mag_16__mean_density_per_ml_bottle on bemovi_mag_16__mean_density_per_ml(bottle);
CREATE INDEX idx_bemovi_mag_16__mean_density_per_ml_species on bemovi_mag_16__mean_density_per_ml(species);
CREATE INDEX idx_bemovi_mag_16__mean_density_per_ml_timestamp on bemovi_mag_16__mean_density_per_ml(timestamp);
CREATE INDEX idx_bemovi_mag_16__mean_density_per_ml_timestamp_bottle on bemovi_mag_16__mean_density_per_ml(timestamp, bottle);


CREATE INDEX idx_bemovi_mag_16__morph_mvt_bottle on bemovi_mag_16__morph_mvt(bottle);
CREATE INDEX idx_bemovi_mag_16__morph_mvt_species on bemovi_mag_16__morph_mvt(species);
CREATE INDEX idx_bemovi_mag_16__morph_mvt_timestamp on bemovi_mag_16__morph_mvt(timestamp);
CREATE INDEX idx_bemovi_mag_16__morph_mvt_timestamp_bottle on bemovi_mag_16__morph_mvt(timestamp, bottle);

CREATE INDEX idx_bemovi_mag_25__mean_density_per_ml_bottle on bemovi_mag_25__mean_density_per_ml(bottle);
CREATE INDEX idx_bemovi_mag_25__mean_density_per_ml_species on bemovi_mag_25__mean_density_per_ml(species);
CREATE INDEX idx_bemovi_mag_25__mean_density_per_ml_timestamp on bemovi_mag_25__mean_density_per_ml(timestamp);
CREATE INDEX idx_bemovi_mag_25__mean_density_per_ml_timestamp_bottle on bemovi_mag_25__mean_density_per_ml(timestamp, bottle);

CREATE INDEX idx_bemovi_mag_25__mean_density_per_ml_cropped_bottle on bemovi_mag_25__mean_density_per_ml_cropped(bottle);
CREATE INDEX idx_bemovi_mag_25__mean_density_per_ml_cropped_species on bemovi_mag_25__mean_density_per_ml_cropped(species);
CREATE INDEX idx_bemovi_mag_25__mean_density_per_ml_cropped_timestamp on bemovi_mag_25__mean_density_per_ml_cropped(timestamp);
CREATE INDEX idx_bemovi_mag_25__mean_density_per_ml_cropped_timestamp_bottle on bemovi_mag_25__mean_density_per_ml_cropped(timestamp, bottle);

CREATE INDEX idx_bemovi_mag_25__mean_density_per_ml_non_cropped_bottle on bemovi_mag_25__mean_density_per_ml_non_cropped(bottle);
CREATE INDEX idx_bemovi_mag_25__mean_density_per_ml_non_cropped_species on bemovi_mag_25__mean_density_per_ml_non_cropped(species);
CREATE INDEX idx_bemovi_mag_25__mean_density_per_ml_non_cropped_timestamp on bemovi_mag_25__mean_density_per_ml_non_cropped(timestamp);
CREATE INDEX idx_bemovi_mag_25__mean_density_per_ml_non_cropped_timestamp_bottle on bemovi_mag_25__mean_density_per_ml_non_cropped(timestamp, bottle);

CREATE INDEX idx_bemovi_mag_25__morph_mvt_bottle on bemovi_mag_25__morph_mvt(bottle);
CREATE INDEX idx_bemovi_mag_25__morph_mvt_species on bemovi_mag_25__morph_mvt(species);
CREATE INDEX idx_bemovi_mag_25__morph_mvt_timestamp on bemovi_mag_25__morph_mvt(timestamp);
CREATE INDEX idx_bemovi_mag_25__morph_mvt_timestamp_bottle on bemovi_mag_25__morph_mvt(timestamp, bottle);

CREATE INDEX idx_bemovi_mag_25__morph_mvt_cropped_bottle on bemovi_mag_25__morph_mvt_cropped(bottle);
CREATE INDEX idx_bemovi_mag_25__morph_mvt_cropped_species on bemovi_mag_25__morph_mvt_cropped(species);
CREATE INDEX idx_bemovi_mag_25__morph_mvt_cropped_timestamp on bemovi_mag_25__morph_mvt_cropped(timestamp);
CREATE INDEX idx_bemovi_mag_25__morph_mvt_cropped_timestamp_bottle on bemovi_mag_25__morph_mvt_cropped(timestamp, bottle);

CREATE INDEX idx_bemovi_mag_25__morph_mvt_non_cropped_bottle on bemovi_mag_25__morph_mvt_non_cropped(bottle);
CREATE INDEX idx_bemovi_mag_25__morph_mvt_non_cropped_species on bemovi_mag_25__morph_mvt_non_cropped(species);
CREATE INDEX idx_bemovi_mag_25__morph_mvt_non_cropped_timestamp on bemovi_mag_25__morph_mvt_non_cropped(timestamp);
CREATE INDEX idx_bemovi_mag_25__morph_mvt_non_cropped_timestamp_bottle on bemovi_mag_25__morph_mvt_non_cropped(timestamp, bottle);

CREATE INDEX idx_flowcam__algae_density_bottle on flowcam__algae_density(bottle);
CREATE INDEX idx_flowcam__algae_density_species on flowcam__algae_density(species);
CREATE INDEX idx_flowcam__algae_density_timestamp on flowcam__algae_density(timestamp);
CREATE INDEX idx_flowcam__algae_density_timestamp_bottle on flowcam__algae_density(timestamp, bottle);

CREATE INDEX idx_flowcam__algae_traits_bottle ON flowcam__algae_traits (bottle);
CREATE INDEX idx_flowcam__algae_traits_species ON flowcam__algae_traits (species);
CREATE INDEX idx_flowcam__algae_traits_timestamp ON flowcam__algae_traits (timestamp);
CREATE INDEX idx_flowcam__algae_traits_timestamp_bottle ON flowcam__algae_traits (timestamp, bottle);
CREATE INDEX idx_flowcam__algae_traits_particle_id ON flowcam__algae_traits (particle_id);
CREATE INDEX idx_flowcam__algae_traits_bottle_particle_id ON flowcam__algae_traits (bottle, particle_id);
CREATE INDEX idx_flowcam__algae_traits_timestamp_particle_id ON flowcam__algae_traits (timestamp, particle_id);
CREATE INDEX idx_flowcam__algae_traits_timestamp_bottle_particle_id ON flowcam__algae_traits (timestamp, bottle, particle_id);

CREATE INDEX idx_flowcytometer__flowcytometer_density_bottle on flowcytometer__flowcytometer_density(bottle);
CREATE INDEX idx_flowcytometer__flowcytometer_density_species on flowcytometer__flowcytometer_density(species);
CREATE INDEX idx_flowcytometer__flowcytometer_density_timestamp on flowcytometer__flowcytometer_density(timestamp);
CREATE INDEX idx_flowcytometer__flowcytometer_density_timestamp_bottle on flowcytometer__flowcytometer_density(timestamp, bottle);

CREATE INDEX idx_flowcytometer__flowcytometer_traits_bottle on flowcytometer__flowcytometer_traits(bottle);
CREATE INDEX idx_flowcytometer__flowcytometer_traits_timestamp on flowcytometer__flowcytometer_traits(timestamp);
CREATE INDEX idx_flowcytometer__flowcytometer_traits_timestamp_bottle on flowcytometer__flowcytometer_traits(timestamp, bottle);
CREATE INDEX idx_flowcytometer__flowcytometer_traits_fsc.a on flowcytometer__flowcytometer_traits("fsc.a");

CREATE INDEX idx_manualcount__manualcount_density_bottle on manualcount__manualcount_density(bottle);
CREATE INDEX idx_manualcount__manualcount_density_species on manualcount__manualcount_density(species);
CREATE INDEX idx_manualcount__manualcount_density_timestamp on manualcount__manualcount_density(timestamp);
CREATE INDEX idx_manualcount__manualcount_density_timestamp_bottle on manualcount__manualcount_density(timestamp, bottle);

CREATE INDEX idx_o2meter__o2meter_bottle on o2meter__o2meter(bottle);
CREATE INDEX idx_o2meter__o2meter_timestamp_bottle on o2meter__o2meter(timestamp, bottle);

CREATE INDEX idx_toc__toc_bottle on toc__toc(bottle);
CREATE INDEX idx_toc__toc_timestamp_bottle on toc__toc(timestamp, bottle);
